apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sla-ping-monitor
resources:
  - namespace.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/configmap.yaml
  - backend/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - postgres/secret.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/configmap.yaml
  - frontend/secret.yaml
  - frontend/ingress.yaml
