apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - db-statefulset.yaml
  - db-service.yaml
  - back-configmap.yaml
  - back-deployment.yaml
  - back-service.yaml
  - front-deployment.yaml
  - front-service.yaml
  - networkpolicy-db.yaml
secretGenerator:
  - name: db-secret
    envs:
      - secrets/db.env
generatorOptions:
  disableNameSuffixHash: true
