apiVersion: apps/v1
kind: Deployment
metadata:
  name: sla-frontend
  labels:
    app: sla-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sla-frontend
  template:
    metadata:
      labels:
        app: sla-frontend
    spec:
      containers:
        - name: frontend
          image: sla-ping-monitor-frontend:local
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: sla-frontend-config
            - secretRef:
                name: sla-frontend-secret
