apiVersion: apps/v1
kind: Deployment
metadata:
  name: sla-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: registry.example.com/sla-ping-monitor-backend:0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sla-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: registry.example.com/sla-ping-monitor-frontend:0.0.1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sla-postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:14
