apiVersion: apps/v1
kind: Deployment
metadata:
  name: sla-backend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sla-frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sla-postgres
spec:
  replicas: 1
