apiVersion: apps/v1
kind: Deployment
metadata:
  name: sla-backend
spec:
  template:
    spec:
      containers:
        - name: backend
          image: sla-ping-monitor-backend:local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sla-frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: sla-ping-monitor-frontend:local
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sla-postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:14
